<?php

echo filter_var(27, FILTER_SANITIZE_NUMBER_FLOAT);
//27

echo filter_var(27.85, FILTER_SANITIZE_NUMBER_FLOAT);
//2785

echo filter_var(27.85, FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);
//27.85

echo filter_var("27XY.85", FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);
//27.85
